# Generated by Django 4.1.7 on 2023-06-07 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='не больше 50 символов', max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('image', models.ImageField(upload_to='shop/news')),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 6, 7, 12, 23, 58, 599312, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('slug', models.SlugField(help_text='Заполняется автоматически')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('reviews', models.TextField(verbose_name='Отзыв')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 6, 7, 12, 23, 58, 601260, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
            ],
        ),
    ]
