# Generated by Django 4.1.7 on 2023-04-11 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 8, 47, 41, 754209, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
